### ISSUE TITLE
Unable to login. looks like they broke it

### ISSUE THREAD

**Issue by chennakrishna8** [andrewstuart/go-robinhood#28]
I am getting Invalid Header error when trying to get a client. Anyone else seeing the same issue?

**Comment by vayias** [comment]
Same here. I will post if I can find a workaround but currently unable to login. cc: @andrewstuart

**Comment by chennakrishna8** [comment]
> Same here. I will post if I can find a workaround but currently unable to login. cc: @andrewstuart

Thank you. I was unable to figure out a work around. Any help is greatly appreciated  :)

**Comment by andrewstuart** [comment]
Alright, I think I got it figured out via the usual method: dev tools on the web login page. Try `github.com/andrewstuart/go-robinhood/v2@v2.1.1-beta.2`, and update `username` to your email address, and I think you should be set!

**Comment by andrewstuart** [comment]
Let me know if that worked and I will merge and tag.

**Comment by andrewstuart** [comment]
cc: @vayias and/or @chennakrishna8

**Comment by andrewstuart** [comment]
Alright, I think I got it figured out via the usual method: dev tools on the web login page. Try `github.com/andrewstuart/go-robinhood/v2@v2.1.1-beta.2`, and update `username` to your email address, and I think you should be set!

Let me know if that worked and I will merge and tag. cc: @vayias and/or @chennakrishna8

**Comment by chennakrishna8** [comment]
@andrewstuart Thank you for looking into this. I tried using the latest version. I am stilll getting Invalid Authorization Header error. I was using my email as the username before too. This is the error message I am seeing

`&{Status:400 Bad Request StatusCode:400 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Allow:[POST, OPTIONS] Content-Length:[93] Content-Security-Policy:[default-src 'none'] Content-Type:[application/json] Date:[Fri, 03 Jun 2022 05:48:23 GMT] Server:[envoy] Trace-Uuid:[5e8d2fdc-0f61-4e51-97a1-10a43c5ac328] X-Content-Type-Options:[nosniff] X-Envoy-Upstream-Service-Time:[310] X-Frame-Options:[SAMEORIGIN] X-Robinhood-Api-Version:[0.0.0] X-Xss-Protection:[1; mode=block]] Body:{cs:0xc00026de40} ContentLength:93 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc000100200 TLS:0xc00038dc30}`

May be they just blocked me.

**Comment by chennakrishna8** [comment]
Alright. I am closing this issue. It worked as soon as I updated the device_token in the code to the one I found from the browser login. I will try to see if they accept a guid.

**Comment by andrewstuart** [comment]
I may still try to see if I can just pull the login page programmatically for the most recent device token to get around this permanently for people.

**Comment by chennakrishna8** [comment]
> I may still try to see if I can just pull the login page programmatically for the most recent device token to get around this permanently for people.

thank you so much.
