### ISSUE TITLE
Multi-factor authentication

### ISSUE THREAD

**Issue by michaelkunzmann-sap** [andrewstuart/go-robinhood#3]
Does go-robinhood support MFA? When I sign in, I get a text message with a code to my phone but I can't find any functionality to send the code back.

**Comment by andrewstuart** [comment]
Just added support in v1.3.0 :smile: 

The Dial call will now return the sentinel error `ErrMFARequired` if mfa is required but no value was specifed via the added `OAuth.MFA`. You can now test the Dial error for the above value (`if cli, err := robinhood.Dial(auth); err == robinhood.ErrMFARequired { // do MFA...`) and then update the OAuth struct with MFA before reattempting a Dial.

Let me know if you have any issues!
