### ISSUE TITLE
How do I use this library / login?

### ISSUE THREAD

**Issue by iseahound** [andrewstuart/go-robinhood#30]
After multiple attempts, I finally figured out that I somehow had the v1 installation instead of the v2 installation, and that the default v2 `astuart.co/go-robinhood/v2` isn't up to date with the GitHub. 

What is a context in Robinhood.dial?

```
 not enough arguments in call to robinhood.Dial
        have (*robinhood.OAuth)
        want (context.Context, oauth2.TokenSource)
```

An updated working example would be appreciated!

**Comment by manugarg** [comment]
You can use context.Background() as the first argument to robinhood.Dial.
