### ISSUE TITLE
Fix url used in GetInstrument

### ISSUE THREAD

**Issue by LoganEvans** [andrewstuart/go-robinhood#6]
https://github.com/andrewstuart/go-robinhood/blob/59eac0a0310997e1e5c2a2dea67072eab7403be8/options.go#L103

There should be an "s" at the end of expiration_date:
s/expiration_date/expiration_dates/

To check that this change works as intended, here's a good request for options with an expiration date on 2019-02-15:
https://api.robinhood.com/options/instruments/?chain_id=1404730f-c77c-4fde-bf57-b8d5ea3bbe7c&expiration_dates=2019-02-15&state=active&tradability=tradable&type=put

In contrast, here's what is currently produced (no "s" on expiration_date):
https://api.robinhood.com/options/instruments/?chain_id=1404730f-c77c-4fde-bf57-b8d5ea3bbe7c&expiration_date=2019-02-15&state=active&tradability=tradable&type=put

This second one includes options that expire on 2019-03-15 and 2019-06-21.

**Comment by andrewstuart** [comment]
Good catch. It's been a while since I've worked on this, but I think that explains some weirdness I was seeing when testing this out. This should be fixed in master/v1.3.1 now.
